---
backservers:
  hosts:
    backend:
      ansible_host: backend

frontservers:
  hosts:
    frontend:
      ansible_host: frontend

dbservers:
  hosts:
    db:
      ansible_host: db

dockerserver:
  hosts:
    docker-vm:
      ansible_host: docker-vm