---
- hosts: backend
# - hosts: all
  pre_tasks:
      - name: Install Java
        apt:
            name: openjdk-21-jdk
            state: present
            update_cache: yes
        become: yes

  tasks:
      - name: "debug appdir"
        ansible.builtin.debug:
          msg: "appdir {{ansible_user_dir}}"

      - name: "Clone the Spring repository"
        git:
            repo: "{{ repo }}"
            dest: "{{ appdir }}"
            version: "{{ branch }}"
            force: yes

      - name: "Populate application.properties"
        lineinfile:
          dest: "{{ appdir }}/src/main/resources/application.properties"
          state: present
          regexp: "^{{item.key}}="
          line: "{{item.key}}={{item.value}}"
        with_items:
          - "{{app.env | dict2items}}"

      - name: "Build the Spring application"
        shell: |
          chmod +x ./mvnw
          ./mvnw package -Dmaven.test.skip
        args:
            chdir: "{{ appdir }}"


      - name: copy spring service file
        template:
          src: ../files/spring.service.j2
          dest: "/etc/systemd/system/spring.service"
        become: yes
        become_user: root
        notify: restart spring

      - name: reload spring service
        service:
          name: spring
          state: restarted
        become: yes

      - name: ensure spring service started
        service:
          name: spring
          state: started
          enabled: yes
        become: yes

  handlers:
  - name: restart spring
    service:
      name: spring
      state: restarted
    become: yes
